// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVvhgP_IMCFibLjKp7m0lNcKflh9uchnY',
    appId: '1:618452689917:web:27afc1c150cf9fdf2a2f94',
    messagingSenderId: '618452689917',
    projectId: 'mboathoscope-697fb',
    authDomain: 'mboathoscope-697fb.firebaseapp.com',
    storageBucket: 'mboathoscope-697fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEZb1mVDQ0pXDlqQIhDzHjhaN1lTymFD8',
    appId: '1:618452689917:android:9fd6d7a614e806f42a2f94',
    messagingSenderId: '618452689917',
    projectId: 'mboathoscope-697fb',
    storageBucket: 'mboathoscope-697fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa3rEtKxMGhrofH_8cJ49nPtrmNMe_Q-8',
    appId: '1:618452689917:ios:19f74e1c73a30b032a2f94',
    messagingSenderId: '618452689917',
    projectId: 'mboathoscope-697fb',
    storageBucket: 'mboathoscope-697fb.appspot.com',
    iosBundleId: 'com.mboathoscope.app',
  );

}